/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ExcalidrawStylusRadialPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// RadialMenu.ts
var import_obsidian = require("obsidian");
var RadialMenu = class {
  constructor(plugin, onClose) {
    this.plugin = plugin;
    this.onClose = onClose;
    this.container = null;
    this.wrapper = null;
    this.overlay = null;
    this.isOpen = false;
    this.targetView = null;
    this.app = plugin.app;
  }
  /**
   * Opens the radial menu at the specified screen coordinates (clientX, clientY).
   */
  open(x, y, targetEl) {
    if (this.isOpen)
      return;
    this.isOpen = true;
    this.targetView = this.resolveExcalidrawView(targetEl);
    this.container = document.createElement("div");
    this.container.className = "excalidraw-stylus-radial-container";
    this.container.style.left = `${x}px`;
    this.container.style.top = `${y}px`;
    this.container.addEventListener("pointerdown", (e) => {
      const target = e.target;
      if (!target.closest(".excalidraw-stylus-radial-item")) {
        e.preventDefault();
        e.stopPropagation();
        this.close();
      }
    });
    this.overlay = document.createElement("div");
    this.overlay.className = "excalidraw-stylus-radial-overlay";
    this.container.appendChild(this.overlay);
    this.wrapper = document.createElement("div");
    this.wrapper.className = "excalidraw-stylus-radial-wrapper";
    this.container.appendChild(this.wrapper);
    const center = document.createElement("div");
    center.className = "excalidraw-stylus-radial-center";
    (0, import_obsidian.setIcon)(center, "pen-tool");
    this.wrapper.appendChild(center);
    const ring = document.createElement("div");
    ring.className = "excalidraw-stylus-radial-ring";
    this.wrapper.appendChild(ring);
    const items = [
      {
        id: "freedraw",
        label: "Pen",
        icon: "pencil",
        action: () => this.executeExcalidrawTool("freedraw")
      },
      {
        id: "eraser",
        label: "Eraser",
        icon: "eraser",
        action: () => this.executeExcalidrawTool("eraser")
      },
      {
        id: "hand",
        label: "Move/Pan",
        icon: "hand",
        action: () => this.executeExcalidrawTool("hand")
      },
      {
        id: "selection",
        label: "Select",
        icon: "mouse-pointer",
        action: () => this.executeExcalidrawTool("selection")
      },
      {
        id: "shapes",
        label: "Shapes",
        icon: "shapes",
        action: () => {
        }
      }
    ];
    let hasSelection = false;
    const ea = window.ExcalidrawAutomate;
    if (ea) {
      try {
        if (this.targetView) {
          ea.setView(this.targetView);
        } else {
          ea.setView("active");
        }
        const selected = ea.getViewSelectedElements();
        hasSelection = selected && selected.length > 0;
      } catch (err) {
        console.error("Failed to check selection", err);
      }
    }
    if (hasSelection) {
      items.push({
        id: "copy",
        label: "Copy",
        icon: "copy",
        action: () => this.executeCopy()
      });
    }
    if (this.plugin.copiedElements && this.plugin.copiedElements.length > 0) {
      items.push({
        id: "paste",
        label: "Paste",
        icon: "clipboard",
        action: () => this.executePaste()
      });
    }
    items.push(
      {
        id: "undo",
        label: "Undo",
        icon: "undo-2",
        action: () => this.executeExcalidrawAction("undo")
      },
      {
        id: "redo",
        label: "Redo",
        icon: "redo-2",
        action: () => this.executeExcalidrawAction("redo")
      }
    );
    items.forEach((item, index) => {
      const itemEl = document.createElement("div");
      itemEl.className = "excalidraw-stylus-radial-item";
      if (item.id === "copy" || item.id === "paste") {
        itemEl.classList.add("is-clipboard");
      } else if (item.id === "undo" || item.id === "redo") {
        itemEl.classList.add("is-history");
      }
      const angle = 360 / items.length * index - 90;
      itemEl.style.setProperty("--angle", `${angle}deg`);
      (0, import_obsidian.setIcon)(itemEl, item.icon);
      const labelEl = document.createElement("span");
      labelEl.className = "excalidraw-stylus-radial-item-label";
      labelEl.innerText = item.label;
      itemEl.appendChild(labelEl);
      let labelTimeout = null;
      let holdTimeout = null;
      let isHolding = false;
      let subMenuContainer = null;
      let hoveredSubItem = null;
      const handlePointerMove = (moveEvent) => {
        if (!isHolding || !subMenuContainer)
          return;
        const elementUnderPointer = document.elementFromPoint(moveEvent.clientX, moveEvent.clientY);
        const subItemEl = elementUnderPointer?.closest(".excalidraw-stylus-radial-subitem");
        const subItems = subMenuContainer.querySelectorAll(".excalidraw-stylus-radial-subitem");
        subItems.forEach((sub) => sub.classList.remove("is-hovered"));
        if (subItemEl) {
          subItemEl.classList.add("is-hovered");
          hoveredSubItem = subItemEl;
        } else {
          hoveredSubItem = null;
        }
      };
      const handlePointerUp = (upEvent) => {
        window.removeEventListener("pointermove", handlePointerMove);
        window.removeEventListener("pointerup", handlePointerUp);
        if (holdTimeout) {
          clearTimeout(holdTimeout);
          holdTimeout = null;
        }
        itemEl.classList.remove("is-active");
        itemEl.classList.remove("show-label");
        if (labelTimeout) {
          clearTimeout(labelTimeout);
          labelTimeout = null;
        }
        const rect = itemEl.getBoundingClientRect();
        const releasedOverItem = upEvent.clientX >= rect.left && upEvent.clientX <= rect.right && upEvent.clientY >= rect.top && upEvent.clientY <= rect.bottom;
        if (item.id === "shapes") {
          upEvent.preventDefault();
          upEvent.stopPropagation();
          if (isHolding) {
            if (hoveredSubItem) {
              const toolId = hoveredSubItem.getAttribute("data-tool-id");
              if (toolId) {
                this.executeExcalidrawTool(toolId);
              }
            } else {
              this.executeExcalidrawTool("rectangle");
            }
            if (subMenuContainer) {
              subMenuContainer.parentNode?.removeChild(subMenuContainer);
              subMenuContainer = null;
            }
            this.close();
          } else {
            this.executeExcalidrawTool("rectangle");
            this.close();
          }
          return;
        }
        if (releasedOverItem) {
          upEvent.preventDefault();
          upEvent.stopPropagation();
          item.action();
          if (item.id !== "undo" && item.id !== "redo") {
            this.close();
          }
        }
      };
      itemEl.addEventListener("pointerdown", (e) => {
        itemEl.classList.add("is-active");
        if (labelTimeout)
          clearTimeout(labelTimeout);
        labelTimeout = setTimeout(() => {
          itemEl.classList.add("show-label");
        }, 500);
        if (item.id === "shapes") {
          isHolding = false;
          hoveredSubItem = null;
          if (holdTimeout)
            clearTimeout(holdTimeout);
          holdTimeout = setTimeout(() => {
            isHolding = true;
            subMenuContainer = this.createSubMenu(itemEl);
          }, 350);
          window.addEventListener("pointermove", handlePointerMove);
          window.addEventListener("pointerup", handlePointerUp);
        } else {
          window.addEventListener("pointerup", handlePointerUp);
        }
      });
      itemEl.addEventListener("pointercancel", (e) => {
        window.removeEventListener("pointermove", handlePointerMove);
        window.removeEventListener("pointerup", handlePointerUp);
        if (holdTimeout)
          clearTimeout(holdTimeout);
        if (subMenuContainer) {
          subMenuContainer.parentNode?.removeChild(subMenuContainer);
          subMenuContainer = null;
        }
        itemEl.classList.remove("is-active");
        itemEl.classList.remove("show-label");
        if (labelTimeout)
          clearTimeout(labelTimeout);
      });
      this.wrapper.appendChild(itemEl);
    });
    document.body.appendChild(this.container);
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        if (this.wrapper) {
          this.wrapper.classList.add("is-open");
        }
      });
    });
  }
  /**
   * Closes the radial menu with fade-out/scale-down transition.
   */
  close() {
    if (!this.isOpen)
      return;
    this.isOpen = false;
    if (this.wrapper) {
      this.wrapper.classList.remove("is-open");
      const onTransitionEnd = () => {
        this.destroy();
      };
      this.wrapper.addEventListener("transitionend", onTransitionEnd, { once: true });
      setTimeout(() => {
        if (this.isOpen === false && this.container) {
          this.destroy();
        }
      }, 300);
    } else {
      this.destroy();
    }
  }
  destroy() {
    if (this.container && this.container.parentNode) {
      this.container.parentNode.removeChild(this.container);
    }
    this.container = null;
    this.wrapper = null;
    this.overlay = null;
    this.onClose();
  }
  resolveExcalidrawView(target) {
    try {
      const leafEl = target.closest(".workspace-leaf");
      if (leafEl) {
        const leaves2 = this.app.workspace.getLeavesOfType("excalidraw");
        for (const leaf of leaves2) {
          if (leaf.containerEl === leafEl) {
            return leaf.view;
          }
        }
      }
      const activeLeaf = this.app.workspace.activeLeaf;
      if (activeLeaf && activeLeaf.view && activeLeaf.view.getViewType() === "excalidraw") {
        return activeLeaf.view;
      }
      const leaves = this.app.workspace.getLeavesOfType("excalidraw");
      if (leaves.length > 0) {
        return leaves[0].view;
      }
    } catch (err) {
      console.error("Failed to resolve Excalidraw view", err);
    }
    return null;
  }
  executeExcalidrawTool(tool) {
    try {
      const ea = window.ExcalidrawAutomate;
      if (ea) {
        if (this.targetView) {
          ea.setView(this.targetView);
        } else {
          ea.setView("active");
        }
        const api = this.targetView?.excalidrawAPI || this.targetView?.excalidrawRef?.current || ea.getExcalidrawAPI();
        if (api && typeof api.setActiveTool === "function") {
          api.setActiveTool({ type: tool });
          if (this.plugin.settings.enableDebug) {
            new import_obsidian.Notice(`Switched to tool: ${tool}`);
          }
          return;
        }
        if (typeof ea.setActiveTool === "function") {
          ea.setActiveTool(tool);
          if (this.plugin.settings.enableDebug) {
            new import_obsidian.Notice(`Switched to tool (direct): ${tool}`);
          }
          return;
        }
        new import_obsidian.Notice("Error: setActiveTool function not found.");
      } else {
        new import_obsidian.Notice("Error: ExcalidrawAutomate is not available on window.");
      }
    } catch (err) {
      console.error(`Failed to set active Excalidraw tool: ${tool}`, err);
      new import_obsidian.Notice(`Failed to set active tool: ${err}`);
    }
  }
  executeExcalidrawAction(action) {
    try {
      const ea = window.ExcalidrawAutomate;
      if (ea) {
        if (this.targetView) {
          ea.setView(this.targetView);
        } else {
          ea.setView("active");
        }
        const api = this.targetView?.excalidrawAPI || this.targetView?.excalidrawRef?.current || ea.getExcalidrawAPI();
        if (api && api.history && (typeof api.history.undo === "function" || typeof api.history.redo === "function")) {
          if (action === "undo" && typeof api.history.undo === "function") {
            api.history.undo();
            if (this.plugin.settings.enableDebug) {
              new import_obsidian.Notice("Executed Undo directly on history API");
            }
            return;
          } else if (action === "redo" && typeof api.history.redo === "function") {
            api.history.redo();
            if (this.plugin.settings.enableDebug) {
              new import_obsidian.Notice("Executed Redo directly on history API");
            }
            return;
          }
        }
        if (api && api.actionManager && typeof api.actionManager.executeAction === "function") {
          api.actionManager.executeAction(action);
          if (this.plugin.settings.enableDebug) {
            new import_obsidian.Notice(`Executed action: ${action}`);
          }
          return;
        }
        if (typeof ea.getInstance === "function") {
          const instance = ea.getInstance();
          if (instance && typeof instance.getApp === "function") {
            const app = instance.getApp();
            if (app && app.actionManager && typeof app.actionManager.executeAction === "function") {
              app.actionManager.executeAction(action);
              if (this.plugin.settings.enableDebug) {
                new import_obsidian.Notice(`Executed action (via instance): ${action}`);
              }
              return;
            }
          }
        }
      }
      const isRedo = action === "redo";
      const isMac = navigator.platform.toUpperCase().indexOf("MAC") >= 0;
      const keyEvent = new KeyboardEvent("keydown", {
        key: isRedo ? "y" : "z",
        code: isRedo ? "KeyY" : "KeyZ",
        ctrlKey: !isMac,
        metaKey: isMac,
        bubbles: true,
        cancelable: true
      });
      const targetElement = document.activeElement || document.querySelector(".excalidraw-container") || document.body;
      if (targetElement) {
        targetElement.dispatchEvent(keyEvent);
        if (this.plugin.settings.enableDebug) {
          new import_obsidian.Notice(`Dispatched KeyboardEvent ${isRedo ? "Ctrl+Y" : "Ctrl+Z"}`);
        }
        return;
      }
      new import_obsidian.Notice("Error: Action manager API is not accessible.");
    } catch (err) {
      console.error(`Failed to execute Excalidraw action: ${action}`, err);
      new import_obsidian.Notice(`Failed to execute action: ${err}`);
    }
  }
  executeCopy() {
    try {
      const ea = window.ExcalidrawAutomate;
      if (ea) {
        if (this.targetView) {
          ea.setView(this.targetView);
        } else {
          ea.setView("active");
        }
        const selected = ea.getViewSelectedElements();
        if (selected && selected.length > 0) {
          this.plugin.copiedElements = JSON.parse(JSON.stringify(selected));
          new import_obsidian.Notice(`Copied ${selected.length} element(s)`);
          const clipboardData = JSON.stringify({
            type: "excalidraw/clipboard",
            elements: selected,
            files: {}
          });
          navigator.clipboard.writeText(clipboardData).catch((err) => {
            console.warn("Could not write to system clipboard: ", err);
          });
        }
      }
    } catch (err) {
      console.error("Failed to copy", err);
      new import_obsidian.Notice(`Failed to copy: ${err}`);
    }
  }
  executePaste() {
    try {
      const copied = this.plugin.copiedElements;
      if (!copied || copied.length === 0)
        return;
      const ea = window.ExcalidrawAutomate;
      if (!ea) {
        new import_obsidian.Notice("ExcalidrawAutomate is not available");
        return;
      }
      ea.reset();
      if (this.targetView) {
        ea.setView(this.targetView);
      } else {
        ea.setView("active");
      }
      const generateId = () => Math.random().toString(36).substring(2, 12);
      const idMap = /* @__PURE__ */ new Map();
      copied.forEach((el) => {
        const newId = generateId();
        idMap.set(el.id, newId);
      });
      const pastedElements = copied.map((el) => {
        const cloned = JSON.parse(JSON.stringify(el));
        cloned.id = idMap.get(el.id);
        if (cloned.groupIds) {
          cloned.groupIds = cloned.groupIds.map((gId) => {
            if (!idMap.has(gId)) {
              idMap.set(gId, generateId());
            }
            return idMap.get(gId);
          });
        }
        if (cloned.boundElements) {
          cloned.boundElements = cloned.boundElements.map((bound) => {
            return {
              ...bound,
              id: idMap.get(bound.id) || bound.id
            };
          });
        }
        if (cloned.startBinding) {
          cloned.startBinding.elementId = idMap.get(cloned.startBinding.elementId) || cloned.startBinding.elementId;
        }
        if (cloned.endBinding) {
          cloned.endBinding.elementId = idMap.get(cloned.endBinding.elementId) || cloned.endBinding.elementId;
        }
        cloned.x += 20;
        cloned.y += 20;
        return cloned;
      });
      pastedElements.forEach((el) => {
        ea.elementsDict[el.id] = el;
      });
      ea.addElementsToView(false, true, true);
      new import_obsidian.Notice(`Pasted ${pastedElements.length} element(s)`);
    } catch (err) {
      console.error("Failed to paste", err);
      new import_obsidian.Notice(`Failed to paste: ${err}`);
    }
  }
  createSubMenu(parentEl) {
    const subContainer = document.createElement("div");
    subContainer.className = "excalidraw-stylus-radial-submenu-container";
    const parentRect = parentEl.getBoundingClientRect();
    const scrollX = window.scrollX || document.documentElement.scrollLeft;
    const scrollY = window.scrollY || document.documentElement.scrollTop;
    const centerX = parentRect.left + parentRect.width / 2 + scrollX;
    const centerY = parentRect.top + parentRect.height / 2 + scrollY;
    subContainer.style.left = `${centerX}px`;
    subContainer.style.top = `${centerY}px`;
    const subItems = [
      { id: "rectangle", label: "Rectangle", icon: "square" },
      { id: "diamond", label: "Diamond", icon: "diamond" },
      { id: "ellipse", label: "Ellipse", icon: "circle" },
      { id: "arrow", label: "Arrow", icon: "arrow-right" },
      { id: "line", label: "Line", icon: "minus" }
    ];
    subItems.forEach((item, index) => {
      const subEl = document.createElement("div");
      subEl.className = "excalidraw-stylus-radial-subitem";
      subEl.setAttribute("data-tool-id", item.id);
      const angle = 360 / subItems.length * index - 90;
      subEl.style.setProperty("--angle", `${angle}deg`);
      (0, import_obsidian.setIcon)(subEl, item.icon);
      const label = document.createElement("span");
      label.className = "excalidraw-stylus-radial-subitem-label";
      label.innerText = item.label;
      subEl.appendChild(label);
      subContainer.appendChild(subEl);
    });
    document.body.appendChild(subContainer);
    requestAnimationFrame(() => {
      subContainer.classList.add("is-open");
    });
    return subContainer;
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  enableDebug: false
};
var ExcalidrawStylusRadialPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.activeMenu = null;
    this.lastPenButtonDownTime = 0;
    this.copiedElements = [];
    this.handlePointerDown = (e) => {
      if (this.settings.enableDebug && e.pointerType === "pen") {
        new import_obsidian2.Notice(`DOWN: btn=${e.button} btns=${e.buttons} pres=${e.pressure}`);
      }
      if (e.pointerType !== "pen")
        return;
      const isSPenButton = e.button === 2 || e.button === 5 || e.buttons === 2;
      if (!isSPenButton)
        return;
      const target = e.target;
      const isInsideExcalidraw = !!target.closest(
        '.excalidraw-container, .workspace-leaf-content[data-type="excalidraw"]'
      );
      if (!isInsideExcalidraw)
        return;
      this.lastPenButtonDownTime = Date.now();
      e.preventDefault();
      e.stopPropagation();
      this.openRadialMenu(e.clientX, e.clientY, target);
    };
    this.handlePointerUp = (e) => {
      if (this.settings.enableDebug && e.pointerType === "pen") {
        new import_obsidian2.Notice(`UP: btn=${e.button} btns=${e.buttons} pres=${e.pressure}`);
      }
      if (e.pointerType !== "pen")
        return;
      const isSPenButton = e.button === 2 || e.button === 5 || e.buttons === 2;
      if (!isSPenButton)
        return;
      const target = e.target;
      const isInsideExcalidraw = !!target.closest(
        '.excalidraw-container, .workspace-leaf-content[data-type="excalidraw"]'
      );
      if (isInsideExcalidraw) {
        e.preventDefault();
        e.stopPropagation();
      }
    };
    this.handleContextMenu = (e) => {
      const target = e.target;
      const isInsideExcalidraw = !!target.closest(
        '.excalidraw-container, .workspace-leaf-content[data-type="excalidraw"]'
      );
      if (!isInsideExcalidraw)
        return;
      const pe = e;
      const pointerType = pe.pointerType;
      if (this.settings.enableDebug) {
        new import_obsidian2.Notice(`CTX: type=${pointerType} btn=${e.button} btns=${pe.buttons}`);
      }
      const isSPenButtonTap = !pointerType || pointerType === "";
      const isRecentSPen = Date.now() - this.lastPenButtonDownTime < 1e3;
      const isPen = pointerType === "pen" && (e.button === 2 || e.button === 5);
      if (isSPenButtonTap || isRecentSPen || isPen) {
        e.preventDefault();
        e.stopPropagation();
        if (!isRecentSPen) {
          this.openRadialMenu(e.clientX, e.clientY, target);
        }
      }
    };
    this.handleCopy = (e) => {
      const target = e.target;
      const isInsideExcalidraw = !!target.closest(
        '.excalidraw-container, .workspace-leaf-content[data-type="excalidraw"]'
      );
      if (!isInsideExcalidraw)
        return;
      setTimeout(() => {
        try {
          const ea = window.ExcalidrawAutomate;
          if (ea) {
            ea.reset();
            ea.setView("active");
            const selected = ea.getViewSelectedElements();
            if (selected && selected.length > 0) {
              this.copiedElements = JSON.parse(JSON.stringify(selected));
            }
          }
        } catch (err) {
          console.error("Failed to cache copied elements", err);
        }
      }, 100);
    };
  }
  async onload() {
    console.log("Loading Excalidraw Stylus Radial Plugin");
    await this.loadSettings();
    this.addSettingTab(new ExcalidrawStylusRadialSettingTab(this.app, this));
    this.registerDomEvent(
      document,
      "pointerdown",
      this.handlePointerDown,
      { capture: true }
    );
    this.registerDomEvent(
      document,
      "pointerup",
      this.handlePointerUp,
      { capture: true }
    );
    this.registerDomEvent(
      document,
      "contextmenu",
      this.handleContextMenu,
      { capture: true }
    );
    this.registerDomEvent(
      document,
      "copy",
      this.handleCopy,
      { capture: true }
    );
  }
  onunload() {
    console.log("Unloading Excalidraw Stylus Radial Plugin");
    this.closeActiveMenu();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  openRadialMenu(x, y, target) {
    this.closeActiveMenu();
    this.activeMenu = new RadialMenu(this, () => {
      this.activeMenu = null;
    });
    this.activeMenu.open(x, y, target);
  }
  closeActiveMenu() {
    if (this.activeMenu) {
      this.activeMenu.close();
      this.activeMenu = null;
    }
  }
};
var ExcalidrawStylusRadialSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Excalidraw Stylus Radial Settings" });
    new import_obsidian2.Setting(containerEl).setName("Enable Debug Mode").setDesc("Show debug Notice toasts on screen for pointer events, buttons, tool switching, and actions.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableDebug).onChange(async (value) => {
        this.plugin.settings.enableDebug = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
